server:
  port: 8090

spring:
  application:
    name: "cards"
  profiles:
    active: qa
  datasource:
    url: jdbc:mysql://localhost:3307/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springstudent
    password: Chicken@69
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://configserver:8071"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "Cards Microservice"
    version: "1.0"

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG
